#!/bin/bash

# search for Includes in main ~/.ssh/config
# check if absolute or relative path see man ssh_config
sshconfigs(){
  CONFIGS=(~/.ssh/config)
  for line in $(grep Include ${CONFIGS} | awk '{print $NF}'); do
    if [[ ${line:0:1} == / || ${line:0:2} == ~[/a-zA-Z.] ]]; then
	CONFIGS+=($line)
    else
	CONFIGS+=(~/.ssh/${line})
    fi
  done
  echo ${CONFIGS[@]}
}

# loop through all sshconfigs() and present everything in fzf-tmux
# start nested tmux session on remote system or fallback to regular ssh if tmux is not installed remotely
ssh-tmux(){
  local selected_host=$(awk '/^Host / {
    host = $2
    desc = ""
    for (i=3; i<=NF; i++) desc = desc " " $i
    if (host !~ "*") print host "\t" desc
    }' $(sshconfigs) | fzf-tmux -p --reverse -1 -0 +m +s --query "$LBUFFER" --prompt="SSH Host > " | cut -f1)

  if [ -n "$selected_host" ]; then
    tmux new-window -n ssh-${selected_host} /usr/bin/ssh -o ConnectTimeout=10 -t "${selected_host}" "tmux new -A 'cat /etc/motd; /bin/bash'" || /usr/bin/ssh -o ConnectTimeout=10 -t "${selected_host}"
  fi
}

ssh-tmux
