#!/bin/bash

function ssh-tmux () {
  local selected_host=$(awk '/^Host / {
    host = $2
    desc = ""
    for (i=3; i<=NF; i++) desc = desc " " $i
    if (host != "*") print host "\t" desc
  }' ~/.ssh/config | fzf-tmux -p --reverse -1 -0 +m +s --query "$LBUFFER" --prompt="SSH Host > " | cut -f1)

  if [ -n "$selected_host" ]; then
    tmux new-window -n ssh-${selected_host} /usr/bin/ssh -o ConnectTimeout=10 -t "${selected_host}" "tmux new -A 'cat /etc/motd; /bin/bash'" || /usr/bin/ssh -o ConnectTimeout=10 -t "${selected_host}"
  fi
}

ssh-tmux
